name: Deploy All Environments

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-dev:
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      environment: dev
      tf_workspace: dev

  deploy-stg:
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      environment: stg
      tf_workspace: stg

  deploy-prod:
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      environment: prod
      tf_workspace: prod
