name: Deploy Workflow
on:
  push:
    branches:
      - main
      - dev
      - stg
      - prd
      - feature/*
      - bugfix/*
  pull_request:
    branches:
      - main
      - dev
      - stg
      - prd
  workflow_dispatch:

jobs:
  scan:
    name: Checkov Scan Job
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
      actions: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Run Checkov with SARIF output (soft fail)
        uses: bridgecrewio/checkov-action@v12
        with:
          output_format: cli,sarif
          output_file_path: console,results.sarif
          soft_fail: true  # Soft fail: does not block PR

      - name: Upload SARIF file to GitHub Security tab
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif


          
    
