name: Terraform Destroy Pipeline

on:
  workflow_dispatch:

jobs:
  destroy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: environments/prod

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan (Destroy)
        run: terraform plan -destroy -out=tfplan_destroy

      - name: Terraform Destroy (Manual Approval)
        run: terraform apply -auto-approve tfplan_destroy
