name: Terraform Destroy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init
        working-directory: ./environments/${{ inputs.environment }}

<<<<<<< HEAD
      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        working-directory: ./environments/${{ inputs.environment }}
=======
      - name: Terraform Plan (Destroy)
        run: terraform plan -destroy -out=tfplan_destroy

      - name: Terraform Destroy (Manual Approval)
        run: terraform apply -auto-approve tfplan_destroy
>>>>>>> 43ef972e23ecb22b0daa6411cfc49331cac14eca
