name: Manual Terraform Deployment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to deploy (dev, stg, prod)"
        required: true
        type: choice
        options:
          - dev
          - stg
          - prod


jobs:
  deploy:
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      environment: ${{ github.event.inputs.environment }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
