name: multi env deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-dev:
    name: Deploy to Dev
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      environment: dev

  deploy-stg:
    name: Deploy to Staging
    needs: deploy-dev           # waiting Dev to finish
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      environment: stg

  deploy-prod:
    name: Deploy to Prod
    needs: deploy-stg           # waiting stg to finish
    uses: ./.github/workflows/terraform-deploy.yml
    with:
      environment: prod
