name: Terraform Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        run: terraform init
        working-directory: ./environments/${{ inputs.environment }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./environments/${{ inputs.environment }}

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./environments/${{ inputs.environment }}
